import type { ApiTab, CorePropRow, EventRow, ModuleInfoRow } from './ApiReference.types';

export const API_TABS: ApiTab[] = ['props', 'events', 'modules'];

export const CORE_PROPS: CorePropRow[] = [
  { prop: 'direction', type: "'horizontal' | 'vertical'", default: "'horizontal'", desc: 'Slide direction' },
  { prop: 'slidesPerView', type: "number | 'auto'", default: '1', desc: 'Number of visible slides' },
  { prop: 'spaceBetween', type: 'number', default: '0', desc: 'Gap between slides (px)' },
  { prop: 'slidesPerGroup', type: 'number', default: '1', desc: 'Slides to advance per swipe' },
  { prop: 'speed', type: 'number', default: '300', desc: 'Transition duration (ms)' },
  { prop: 'loop', type: 'boolean', default: 'false', desc: 'Enable infinite loop' },
  { prop: 'centeredSlides', type: 'boolean', default: 'false', desc: 'Center active slide' },
  { prop: 'initialSlide', type: 'number', default: '0', desc: 'Starting slide index' },
  { prop: 'grabCursor', type: 'boolean', default: 'false', desc: 'Show grab cursor' },
  { prop: 'effect', type: 'RailEffect', default: "'slide'", desc: 'Transition effect type' },
  { prop: 'allowTouchMove', type: 'boolean', default: 'true', desc: 'Enable touch/drag' },
  { prop: 'threshold', type: 'number', default: '5', desc: 'Minimum drag distance (px)' },
  { prop: 'resistance', type: 'boolean', default: 'true', desc: 'Edge resistance' },
  { prop: 'autoHeight', type: 'boolean', default: 'false', desc: 'Adapt height to active slide' },
  { prop: 'watchSlidesProgress', type: 'boolean', default: 'false', desc: 'Track slide visibility' },
  { prop: 'breakpoints', type: 'Record<number, Partial<RailOptions>>', default: '\u2014', desc: 'Responsive option overrides' },
  { prop: 'modules', type: 'RailModuleFactory[]', default: '[]', desc: 'Active modules' },
  { prop: 'onRail', type: '(instance) => void', default: '\u2014', desc: 'Rail instance callback' },
];

export const EVENTS: EventRow[] = [
  { event: 'init', args: '()', desc: 'Carousel initialized' },
  { event: 'destroy', args: '()', desc: 'Carousel destroyed' },
  { event: 'slideChange', args: '(index, prevIndex)', desc: 'Active slide changed' },
  { event: 'transitionStart', args: '()', desc: 'Transition started' },
  { event: 'transitionEnd', args: '()', desc: 'Transition finished' },
  { event: 'touchStart', args: '(TouchData)', desc: 'Touch/drag started' },
  { event: 'touchMove', args: '(TouchData)', desc: 'Touch/drag moving' },
  { event: 'touchEnd', args: '(TouchData)', desc: 'Touch/drag ended' },
  { event: 'resize', args: '()', desc: 'Container resized' },
  { event: 'reachBeginning', args: '()', desc: 'First slide reached' },
  { event: 'reachEnd', args: '()', desc: 'Last slide reached' },
  { event: 'progress', args: '(progress: number)', desc: 'Progress updated (0\u20131)' },
  { event: 'breakpoint', args: '(breakpoint: number)', desc: 'Active breakpoint changed' },
  { event: 'autoplayStart', args: '()', desc: 'Autoplay started' },
  { event: 'autoplayStop', args: '()', desc: 'Autoplay stopped' },
  { event: 'storyProgress', args: '(slideIndex, progress)', desc: 'Story progress updated' },
  { event: 'storyComplete', args: '()', desc: 'All stories viewed' },
];

export const MODULE_INFO: ModuleInfoRow[] = [
  { name: 'Navigation', cat: 'core', desc: 'Previous/next arrows with disabled states' },
  { name: 'Pagination', cat: 'core', desc: 'Bullets, fraction, progressbar pagination' },
  { name: 'Scrollbar', cat: 'core', desc: 'Draggable scrollbar indicator' },
  { name: 'Autoplay', cat: 'core', desc: 'Automatic slide transitions' },
  { name: 'Keyboard', cat: 'control', desc: 'Arrow/Page key navigation' },
  { name: 'Mousewheel', cat: 'control', desc: 'Scroll wheel navigation' },
  { name: 'Virtual', cat: 'perf', desc: 'Render only visible slides' },
  { name: 'Parallax', cat: 'visual', desc: 'Data-attribute parallax effects' },
  { name: 'FreeMode', cat: 'control', desc: 'Momentum-based free scrolling' },
  { name: 'Grid', cat: 'layout', desc: 'Multi-row grid layout' },
  { name: 'Manipulation', cat: 'core', desc: 'Add, remove, reorder slides' },
  { name: 'Zoom', cat: 'visual', desc: 'Pinch/double-click to zoom' },
  { name: 'Controller', cat: 'sync', desc: 'Synchronize multiple Rail instances' },
  { name: 'A11y', cat: 'a11y', desc: 'ARIA labels and live regions' },
  { name: 'History', cat: 'nav', desc: 'Browser history integration' },
  { name: 'HashNavigation', cat: 'nav', desc: 'URL hash-based navigation' },
  { name: 'Thumbs', cat: 'sync', desc: 'Thumbnail gallery sync' },
  { name: 'EffectFade', cat: 'effect', desc: 'Crossfade transition' },
  { name: 'EffectCube', cat: 'effect', desc: '3D cube rotation' },
  { name: 'EffectFlip', cat: 'effect', desc: '3D card flip' },
  { name: 'EffectCoverflow', cat: 'effect', desc: '3D coverflow' },
  { name: 'EffectCards', cat: 'effect', desc: 'Stacked cards' },
  { name: 'EffectCreative', cat: 'effect', desc: 'Custom transforms' },
  { name: 'StoryMode', cat: 'special', desc: 'Instagram-style stories' },
];

export const CAT_COLORS: Record<string, string> = {
  core: '#06b6d4',
  control: '#8b5cf6',
  perf: '#f59e0b',
  visual: '#ec4899',
  layout: '#22c55e',
  sync: '#3b82f6',
  a11y: '#10b981',
  nav: '#6366f1',
  effect: '#f97316',
  special: '#ef4444',
};
